name: Run SimplyLang Tests & Linting

on:
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for running tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls the latest code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use any Python version you need

      - name: Install Dependencies
        run: |
          pip install -r builder/requirements.txt  # Install required dependencies
          pip install pylint black  # Install linting tools

      - name: Run SimplyLang Tests
        run: python src/simply.py tests/system/test.simply  # Run the test.simply file

      - name: Run Linter (Pylint)
        run: pylint src/ || true  # Prevent failure due to linting issues

      - name: Check Code Formatting (Black)
        run: black --check src/ || true  # Prevent failure due to formatting issues
